plantdata = {
    "a.k.e.e.": {
        "name": "A.K.E.E.",
        "sun cost": "175",
        "recharge": "5 seconds",
        "toughness": "300",
        "damage": "0/50/40/30 damage per shot (the first, second, third and fourth zombies)",
        "range": "Lobbed/Multi-Hit",
        "family": "Arma-mint",
        "description": "A.K.E.E.s lob projectiles that bounce from zombie to zombie.",
        "image": "/assets/plants/A.K.E.E..png"
        },
    "ail-mint": {
        "name": "Ail-mint",
        "sun cost": "0",
        "recharge": "85 seconds",
        "duration": "11 seconds",
        "weakness": "(immune to poison effect)",
        "family": "Ail-mint",
        "description": "Ail-mints poison all zombies when planted and provide a temporary boost to all Ail-mint Family plants on the lawn.",
        "image": "/assets/plants/Ail-mint.png"
        },
    "aloe": {
        "name": "Aloe",
        "sun cost": "75",
        "recharge": "20 seconds",
        "toughness": "450",
        "family": "Reinforce-mint",
        "description": "Aloes heal injured plants to their immediate right when that plant is below a certain amount of health.",
        "image": "/assets/plants/Aloe.png"
        },
    "appease-mint": {
        "name": "Appease-mint",
        "sun cost": "0",
        "recharge": "85 seconds",
        "duration": "6 seconds",
        "family": "Appease-mint",
        "description": "Appease-mints fire a volley of huge peas that break into smaller peas and provide a temporary boost to all Appease-mint Family plants on the lawn.",
        "image": "https://static.wikia.nocookie.net/plantsvszombies/images/6/68/Appease-mint2.png/revision/latest?cb=20190826075335",
        },
    "apple mortar": {
        "name": "Apple Mortar",
        "sun cost": "250",
        "recharge": "8 seconds",
        "toughness": "300",
        "damage": "30 damage per shot",
        "area": "3x3",
        "range": "Lobbed",
        "family": "Arma-mint",
        "description": "Apple Mortars lob apple cores that damage and briefly stun zombies over three lanes.",
        "image": "/assets/plants/Apple Mortar.png"
        },
    "arma-mint": {
        "name": "Arma-mint",
        "sun cost": "0",
        "recharge": "85 seconds",
        "damage": "1200 dps",
        "duration": "6 seconds",
        "family": "Arma-mint",
        "description": "Arma-mints launch a volley of heavy stunning artillery projectiles and provide a temporary boost to all Arma-mint Family plants on the lawn.",
        "image": "/assets/plants/Arma-mint.png"
        },
    "banana launcher": {
        "name": "Banana Launcher",
        "sun cost": "500",
        "recharge": "5 seconds",
        "damage": "1200 damage per shot in a 1x3 area",
        "area": "Tile",
        "range": "Anywhere on lawn",
        "usage": "Tap to arm, tap on target tile to fire",
        "special": "On impact, explodes in small area",
        "family": "Arma-mint",
        "description": "Banana Launchers can fire explosive bananas at any tile on the lawn.",
        "image": "/assets/plants/Banana Launcher.png"
        },
    "blastberry vine": {
        "name": "Blastberry Vine",
        "sun cost": "175",
        "recharge": "10 seconds",
        "damage": "15 DPS per bomblet",
        "family": "Arma-mint",
        "description": "Blastberry Vines can be planted on top of other plants to provide increased defense and an additional attack in the form of lobbed projectiles that break into explosive bomblets.",
        "image": "/assets/plants/Blastberry Vine.png"
        },
    "bloomerang": {
        "name": "Bloomerang",
        "sun cost": "175",
        "recharge": "5 seconds",
        "damage": "20",
        "toughness": "300",
        "range": "Multi-Hit",
        "powerup": "Duration",
        "family": "Spear-mint",
        "description": "Bloomerangs can hit multiple targets in their lane, twice each coming and going!",
        "image": "/assets/plants/Bloomerang.png"
        },
    "blooming heart": {
        "name": "Blooming Heart",
        "sun cost": "150",
        "recharge": "5 seconds",
        "damage": "40 damage per shot, increases by 10 with each attack hitting a single zombie, up to 5 times",
        "range": "Lobbed",
        "family": "Ail-mint",
        "description": "Blooming Hearts lob projectiles that infatuate zombies, causing increasing damage the more that hit.",
        "image": "/assets/plants/Blooming Heart.png"
        },
    "blover": {
        "name": "Blover",
        "sun cost": "50",
        "recharge": "5 seconds",
        "usage": "Single use, instant",
        "special": "Blows away all flying zombies",
        "range": "Full Board",
        "family": "Contain-mint",
        "description": "Blovers blow away all zombies in air",
        "image": "/assets/plants/Blover.png"
        },
    "bombard-mint": {
        "name": "Bombard-mint",
        "sun cost": "0",
        "recharge": "85 seconds",
        "damage": "1800 damage per shot",
        "duration": "6 seconds",
        "family": "Bombard-mint",
        "description": "Bombard-mints set off a number of explosions on the board and provide a temporary boost to all Bombard-mint Family plants on the lawn.",
        "image": "/assets/plants/Bombard-mint.png"
        },
    "bonk choy": {
        "name": "Bonk Choy",
        "sun cost": 150,
        "recharge": 5,
        "damage": 15,
        "toughness": 300,
        "range": "Close",
        "powerup": "Duration",
        "description": "Bonk Choys rapidly punch nearby enemies that are ahead or behind them.",
        "image": "/assets/plants/Bonk Choy.png"
        },
    "boom balloon flower": {
        "name": "Boom Balloon Flower",
        "sun cost": "350",
        "recharge": "5",
        "damage": "575 (per balloon)",
        "toughness": "300",
        "usage": "Tap or drag from Boom Balloon Flower to move a balloon to a tile",
        "family": "Bombard-mint",
        "description": "Boom Balloon Flowers spawn exploding balloons that can be placed anywhere on the lawn as traps for zombies.",
        "image": "/assets/plants/Boom Balloon Flower.png"
        },
    "bowling bulb": {
        "name": "Bowling Bulb",
        "sun cost": "200",
        "recharge": "5 seconds",
        "damage": "40 damage per shot (aquamarine bulb)",
        "range": "Multi-Hit",
        "family": "Appease-mint",
        "description": "Bowling Bulbs rolls shots that can bounce into multiple zombies.",
        "image": "/assets/plants/Bowling Bulb.png"
        },
    "cabbage-pult": {
        "name": "Cabbage-pult",
        "sun cost": "100",
        "recharge": "5 seconds",
        "damage": "40",
        "range": "Lobbed",
        "family": "Arma-mint",
        "description": "Cabbage-pults hurl cabbages at the enemy.",
        "image": "/assets/plants/Cabbage-pult.png"
        },
    "caulipower": {
        "name": "Caulipower",
        "sun cost": "250 (300 in Chinese version)",
        "recharge": "45 seconds",
        "toughness": "300 damage per shot",
        "range": "Full Board",
        "special": "Hovers above ground or water",
        "family": "Enchant-mint",
        "description": "Caulipowers use their mental powers to hypnotize random zombies and turn them against their former friends.",
        "image": "/assets/plants/Caulipower.png"
        },
    "celery stalker": {
        "name": "Celery Stalker",
        "sun cost": "50",
        "recharge": "15 seconds",
        "damage": "100 damage per shot every 0.5 seconds",
        "toughness": "1200 damage per shot",
        "special": "Waits until zombies pass over it, then pops up and attacks",
        "weakness": "(instantly kills it)",
        "family": "Enforce-mint",
        "description": "Celery Stalkers wait until zombies pass, then pop up and bash them from behind.",
        "image": "/assets/plants/Celery Stalker.png"
        },
    "chard guard": {
        "name": "Chard Guard",
        "sun cost": "75",
        "recharge": "15 seconds",
        "toughness": "1500",
        "special": "Hurls zombies back (*3)",
        "family": "Reinforce-mint",
        "description": "Chard Guards are defensive blockers that can hurl zombies backwards.",
        "image": "/assets/plants/Chard Guard.png"
        },
    "cherry bomb": {
        "name": "Cherry Bomb",
        "sun cost": "150",
        "recharge": "35 seconds",
        "damage": "Massive",
        "area": "3*3",
        "usage": "Single use, instant",
        "family": "Bombard-mint",
        "description": "Cherry Bombs can blow up all zombies in an area. They have a short fuse so plant them near zombies.",
        "image": "/assets/plants/Cherry Bomb.png"
        },
    "chili bean": {
        "name": "Chili Bean",
        "sun cost": "50",
        "recharge": "20 seconds",
        "usage": "When eaten",
        "special": "Eating zombie is destroyed and releases stunning gas",
        "family": "Ail-mint",
        "description": "Chili Beans deliver a crippling bout of gastrointestinal distress.",
        "image": "/assets/plants/Chili Bean.png"
        },
    "citron": {
        "name": "Citron",
        "sun cost": "350",
        "recharge": "5 seconds",
        "damage": "800",
        "area": "single",
        "family": "Fila-mint",
        "description": "Citrons shoot powerful balls of plasma",
        "image": "/assets/plants/Citron.png"
        },
    "coconut cannon": {
        "name": "Coconut Cannon",
        "sun cost": "400",
        "recharge": "5 seconds",
        "damage": "900",
        "toughness": "300",
        "area": "3*3",
        "usage": "Tap to fire",
        "special": "On impact, explodes in medium area",
        "family": "Arma-mint",
        "description": "Coconut Cannons fire down a single lane, causing a medium explosion on impact.",
        "image": "/assets/plants/Coconut Cannon.png"
        },
    "cold snapdragon": {
        "name": "Cold Snapdragon",
        "sun cost": "150, 250 (China)",
        "recharge": "5 seconds",
        "damage": "30 damage per shot (60 in the Chinese version)",
        "range": "Close",
        "special": "Slows and damages zombies in the 6 tiles in front of it",
        "family": "Winter-mint",
        "description": "Cold Snapdragons breathe icy mist into 6 adjacent tiles that both slows and damage zombies.",
        "image": "/assets/plants/Cold Snapdragon.png"
        },
    "conceal-mint": {
        "name": "Conceal-mint",
        "sun cost": "0",
        "recharge": "85 seconds",
        "duration": "6 seconds",
        "family": "Conceal-mint",
        "description": "Conceal-mints power up all shadow plants on the lawn, drag some number of zombies to their doom, and provide an additional temporary boost to Conceal-mint Family plants.",
        "image": "/assets/plants/Conceal-mint.png"
        },
    "dartichoke": {
        "name": "Dartichoke",
        "sun cost": "225",
        "recharge": "8.5 seconds",
        "damage": "75 damage per shot",
        "range": "Straight",
        "usage": "Has a limited supply of darts, then must recharge",
        "special": "Each shot has a chance to do critical damage",
        "family": "Spear-mint",
        "description": "Dartichokes fire high-damage darts down the lane, prioritizing especially dangerous zombies such as Wizards, Octo Zombies and Healers.",
        "image": "/assets/plants/Dartichoke.png"
        },
    "dazey chain": {
        "name": "Dazey Chain",
        "sun cost": "150",
        "recharge": "5 seconds",
        "damage": "20 damage per shot per open flower",
        "family": "Contain-mint",
        "description": "Dazey Chains grow through stages, becoming more powerful and releasing a stunning puff of gas at each stage.",
        "image": "/assets/plants/Dazey Chain.png"
        },
    "draftodil": {
        "name": "Draftodil",
        "sun cost": "100",
        "recharge": "5 seconds",
        "damage": "15 damage per shot",
        "toughness": "300 damage per shot",
        "usage": "Briefly stuns non-flying zombies",
        "special": "Air cannon knocks critters, imps and shrunken zombies off the lawn",
        "family": "Contain-mint",
        "description": "Draftodils windmill constantly, slowing flying zombies, and also shoot air cannon blasts that knock flying zombies off the lawn.",
        "image": "/assets/plants/Draftodil.png"
        },
    "dusk lobber": {
        "name": "Dusk Lobber",
        "sun cost": "150 (200 in China)",
        "recharge": "10 seconds",
        "damage": "30 damage per shot, with 25 damage per shot splash damage in a 3x3 area",
        "area": "3x3",
        "range": "Lobbed",
        "family": "Conceal-mint",
        "description": "Dusk Lobbers are shadow plants that lob explosive buds down the lane. When powered Dusk Lobbers can lob buds down three lane.",
        "image": "/assets/plants/Dusk Lobber.png"
        },
    "e.m.peach": {
        "name": "E.M.Peach",
        "sun cost": "25",
        "recharge": "25 seconds",
        "usage": "Single use, instant",
        "special": "Disables machines",
        "range": "200(5*5)",
        "family": "Fila-mint",
        "description": "E.M.Peaches explode and disable all machines in an area.",
        "image": "/assets/plants/E.M.Peach.png"
        },
    "electrici-tea": {
        "name": "Electrici-tea",
        "sun cost": "125",
        "recharge": "15 seconds",
        "damage": "950 damage per shot (explosion)",
        "range": "3 damage per shot (passive electric zaps)",
        "special": "Multi-Hit",
        "weakness": "Zombies Zapped",
        "family": "Fila-mint",
        "description": "Electrici-teas wait and emit zaps of electrical energy until they are eaten, at which point the eating zombies explode in a flurry of electrical discharge",
        "image": "/assets/plants/Electrici-tea.png"
        },
    "enchant-mint": {
        "name": "Enchant-mint",
        "sun cost": "0",
        "recharge": "85 seconds",
        "duration": "11 seconds",
        "family": "Enchant-mint",
        "description": "Enchant-mints randomly hypnotize a number of zombies and provide a temporary boost to all Enchant-mint Family plants on the lawn.",
        "image": "/assets/plants/Enchant-mint.png"
        },
    "endurian": {
        "name": "Endurian",
        "sun cost": "100",
        "recharge": "15 seconds",
        "damage": "20",
        "toughness": "3000",
        "family": "Reinforce-mint",
        "description": "Endurians are defensive plants that deal damage to zombies attacking them.",
        "image": "/assets/plants/Endurian.png"
        },
    "enforce-mint": {
        "name": "Enforce-mint",
        "sun cost": "0",
        "recharge": "85 seconds",
        "duration": "8 seconds",
        "family": "Enforce-mint",
        "description": "Enforce-mints shrink a number of zombies when planted and provide a temporary boost to all Enforce-mint Family plants on the lawn.",
        "image": "/assets/plants/Enforce-mint.png"
        },
    "enlighten-mint": {
        "name": "Enlighten-mint",
        "sun cost": "0",
        "recharge": "85 seconds",
        "duration": "5 seconds",
        "family": "Enlighten-mint",
        "description": "Enlighten-mints give a burst of sun when planted, and provide an additional temporary boost to Enlighten-mint Family plants.",
        "image": "/assets/plants/Enlighten-mint.png"
        },
    "escape root": {
        "name": "Escape Root",
        "sun cost": "50",
        "recharge": "20 seconds",
        "usage": "Instant",
        "family": "Bombard-mint",
        "description": "Escape Roots explode on contact, and can be swapped with other plants that are in danger.",
        "image": "/assets/plants/Escape Root.png"
        },
    "explode-o-nut": {
        "name": "Explode-O-Nut",
        "sun cost": "50",
        "recharge": "10 seconds",
        "toughness": "3000 damage per shot",
        "weakness": "(Immune to explosion)",
        "family": "Bombard-mint",
        "description": "Explode-O-Nuts provide protection, and when their shells are eaten, they explode to blow up zombies.",
        "image": "/assets/plants/Explode-O-Nut.png"
        },
    "explode-o-vine": {
        "name": "Explode-o-Vine",
        "sun cost": "150",
        "recharge": "10 seconds",
        "toughness": "1500 damage per shot",
        "usage": "can be planted on top of non-vine plants",
        "family": "Bombard-mint",
        "description": "Explode-O-Vines detonate an explosion with knockback when planted, and then a larger explosion when eaten.",
        "image": "/assets/plants/Explode-o-Vine.png"
        },
    "fila-mint": {
        "name": "Fila-mint",
        "sun cost": "0",
        "recharge": "85 seconds",
        "damage": "150 damage per shot",
        "duration": "6 seconds",
        "family": "Fila-mint",
        "description": "Fila-mints do electric damage and provide a temporary boost to all Fila-mint Family plants on the lawn.",
        "image": "/assets/plants/Fila-mint.png"
        },
    "fume-shroom": {
        "name": "Fume-shroom",
        "sun cost": "125",
        "recharge": "5 seconds",
        "damage": "40 damage per shot",
        "area": "1x4",
        "family": "Ail-mint",
        "description": "Fume-shrooms shoot fumes that damage all zombies in an area.",
        "image": "/assets/plants/Fume-shroom.png"
        },
    "garlic": {
        "name": "Garlic",
        "sun cost": "50",
        "recharge": "20 seconds",
        "toughness": "600 damage per shot",
        "area": "Single",
        "range": "Touch",
        "family": "Ail-mint",
        "description": "Garlic diverts zombies into other lanes.",
        "image": "/assets/plants/Garlic.png"
        },
    "ghost pepper": {
        "name": "Ghost Pepper",
        "sun cost": "75, 100 (China)",
        "recharge": "15 seconds",
        "damage": "30 damage per shot every 0.5 seconds",
        "range": "Front & Back",
        "family": "Pepper-mint",
        "description": "Ghost Peppers haunt zombies that pass by and explode after a limited time.",
        "image": "/assets/plants/Ghost Pepper.png"
        },
    "gloom vine": {
        "name": "Gloom Vine",
        "sun cost": "125",
        "recharge": "5 seconds",
        "damage": "45 damage per shot",
        "toughness": "250 damage per shot",
        "range": "3x3",
        "special": "Powers shadow plants within",
        "family": "Conceal-mint",
        "description": "Gloom Vines power individual shadow plants and shoot zombie-damaging gloom in eight directions.",
        "image": "/assets/plants/Gloom Vine.png"
        },
    "gold bloom": {
        "name": "Gold Bloom",
        "sun cost": "0",
        "recharge": "75 seconds",
        "usage": "Instant",
        "family": "Enlighten-mint",
        "description": "Gold Blooms produce a burst of sun all at once.",
        "image": "/assets/plants/Gold Bloom.png"
        },
    "gold leaf": {
        "name": "Gold Leaf",
        "sun cost": "50",
        "recharge": "30 seconds",
        "special": "creates sun every 20 seconds",
        "usage": "Single use,instant",
        "description": "Gold Leaves create a Gold Tile on planting.",
        "image": "/assets/plants/Gold Leaf.png"
        },
    "grapeshot": {
        "name": "Grapeshot",
        "sun cost": "150",
        "recharge": "35 seconds",
        "damage": "1800 damage per shot (explosion)",
        "area": "3x3",
        "special": "200 damage per shot (grapes).(Immune to explosion)",
        "usage": "Instant",
        "weakness": "(deflects grapes)",
        "family": "Bombard-mint",
        "description": "Grapeshots explode and scatter bouncing projectiles in eight directions.",
        "image": "/assets/plants/Grapeshot.png"
        },
    "grave buster": {
        "name": "Grave Buster",
        "sun cost": "0",
        "recharge": "10 seconds",
        "toughness": "Normal",
        "usage": "Single use, must be planted on graves",
        "special": "Removes graves",
        "family": "Contain-mint",
        "description": "Grave Busters consume graves they're planted on.",
        "image": "/assets/plants/Grave Buster.png"
        },
    "grimrose": {
        "name": "Grimrose",
        "sun cost": "75",
        "recharge": "20 seconds",
        "range": "Lane",
        "usage": "Single",
        "family": "Conceal-mint",
        "description": "Grimroses are shadow plants that behave like landbound Tangle Kelps, dragging up to 3 zombies into the dirt.",
        "image": "/assets/plants/Grimrose.png"
        },
    "gumnut": {
        "name": "Gumnut",
        "sun cost": "125",
        "recharge": "12 seconds",
        "usage": "Best used against Gargantuars & Football Mechs",
        "special": "Stronger zombies form stronger barriers",
        "weakness": "(can easily remove gum from gummed zombies when teleporting them)",
        "family": "Reinforce-mint",
        "description": "Gumnuts pop sticky gum onto zombies, pinning them in place and causing them to block other zombies behind them.",
        "image": "/assets/plants/Gumnut.png"
        },
    "headbutter lettuce": {
        "name": "Headbutter Lettuce",
        "sun cost": "175",
        "recharge": "7 seconds",
        "damage": "100 damage per shot",
        "toughness": "900 damage per shot",
        "usage": "Resists damage with high health",
        "family": "Enforce-mint",
        "description": "Headbutter Lettuces bash zombies in front and behind while occasionally buttering zombies.",
        "image": "/assets/plants/Headbutter Lettuce.png"
        },
    "heath seeker": {
        "name": "Heath Seeker",
        "sun cost": "125",
        "recharge": "20 seconds",
        "damage": "560 dps",
        "range": "Full Board",
        "special": "can target from anywhere on the lawn",
        "family": "Spear-mint",
        "description": "Heath Seekers are Spear-mint family instant-use plants that burst into a storm of homing, piercing darts.",
        "image": "/assets/plants/Heath Seeker.png"
        },
    "hocus crocus": {
        "name": "Hocus Crocus",
        "sun cost": "200",
        "recharge": "20 seconds",
        "damage": "100 damage per shot",
        "special": "Each teleportation also does damage",
        "family": "Enchant-mint",
        "description": "Hocus Crocuses use slick sleight-of-petal chicanery to magic zombies close to your home all the way back to the rightmost part of the lawn.",
        "image": "/assets/plants/Hocus Crocus.png"
        },
    "holly barrier": {
        "name": "Holly Barrier",
        "sun cost": "150",
        "recharge": "15 seconds",
        "damage": "20 damage per shot (plant and barriers)",
        "toughness": "3000 dps",
        "area": "Tile",
        "usage": "Tap to arm, tap on target tile to fire",
        "family": "Reinforce-mint",
        "description": "Holly Barrier deals damage to zombies attacking him, and can launch 3 prickly barrier leaves to knock back and damage zombies.",
        "image": "/assets/plants/Holly Barrier.png"
        },
    "homing thistle": {
        "name": "Homing Thistle",
        "sun cost": "250",
        "recharge": "15 seconds",
        "damage": "40 damage per shot",
        "range": "Full board",
        "family": "Spear-mint",
        "description": "Homing Thistles fire seeking shots at targets that are closest to home.",
        "image": "/assets/plants/Homing Thistle.png"
        },
    "hot potato": {
        "name": "Hot Potato",
        "sun cost": "0",
        "recharge": "10 seconds",
        "usage": "Single use, instant",
        "special": "Melts an ice block",
        "family": "Pepper-mint",
        "description": "Hot Potatoes melt the ice blocks they're planted on.",
        "image": "/assets/plants/Hot Potato.png"
        },
    "iceberg lettuce": {
        "name": "Iceberg Lettuce",
        "sun cost": "0",
        "recharge": "20 seconds",
        "special": "Explodes, temporarily freezing a zombie",
        "range": "Touch",
        "usage": "Single use, on contact",
        "family": "Winter-mint",
        "description": "Iceberg Lettuces freeze a zombie when stepped on.",
        "image": "/assets/plants/Iceberg Lettuce.png"
        },
    "imp pear": {
        "name": "Imp Pear",
        "sun cost": "0",
        "recharge": "5 seconds",
        "damage": "10%",
        "toughness": "300",
        "family": "Ail-mint",
        "description": "When zombies eat Imp Pears, they become Imps. When Imps eat Imp Pears, they are destroyed, releasing stunning gas.",
        "image": "/assets/plants/Imp Pear.png"
        },
    "infi-nut": {
        "name": "Infi-nut",
        "sun cost": "75",
        "recharge": "15 seconds",
        "damage": "2000",
        "special": "Regenerates health over time",
        "weakness": "Crushing zombies",
        "family": "Reinforce-mint",
        "description": "Infi-nuts are weaker than Wall-nuts, but they regain health over time.",
        "image": "/assets/plants/Infi-nut.png"
        },
    "intensive carrot": {
        "name": "Intensive Carrot",
        "sun cost": "100",
        "recharge": "20 seconds",
        "area": "Tile",
        "usage": "Single use, instant",
        "family": "Enchant-mint",
        "description": "Intensive Carrots bring eaten plants back to life.",
        "image": "/assets/plants/Intensive Carrot.png"
        },
    "jack o' lantern": {
        "name": "Jack O' Lantern",
        "sun cost": "225",
        "recharge": "20 seconds",
        "damage": "300 damage per shot per second",
        "area": "1x3",
        "special": "Fire recharges over time",
        "weakness": "(Immune to fire)",
        "family": "Pepper-mint",
        "description": "Jack O' Lanterns spray fire down a lane, doing extensive burning damage over a short distance.",
        "image": "/assets/plants/Jack Lantern.png"
        },
    "jalapeno": {
        "name": "Jalapeno",
        "sun cost": "125",
        "recharge": "35 seconds",
        "damage": "1800 damage per shot to every affected enemy",
        "area": "Lane",
        "usage": "Single use, instant",
        "weakness": "(Immune to fire)",
        "family": "Pepper-mint",
        "description": "Jalapenos destroy an entire lane of zombies.",
        "image": "/assets/plants/Jalapeno.png"
        },
    "kernel-pult": {
        "name": "Kernel-pult",
        "sun cost": "100",
        "recharge": "5 seconds",
        "range": "Lobbed",
        "special": "Butter immobilizes zombies",
        "family": "Arma-mint",
        "description": "Kernel-pults fling corn kernels and immobilizing butter at zombies.",
        "image": "/assets/plants/Kernel-pult.png"
        },
    "kiwibeast": {
        "name": "Kiwibeast",
        "sun cost": "175",
        "recharge": "15 seconds",
        "damage": "40 damage per shot (first stage),50 damage per shot (second stage),70 damage per shot (third stage)",
        "toughness": "Elevated",
        "area": "1x1 (first stage),3x3 (second stage),5x5 (third stage)",
        "family": "Enforce-mint",
        "description": "Kiwibeasts emit damaging thumps, and become bigger and more powerful the more they are hurt by zombies.",
        "image": "/assets/plants/Kiwibeast.png"
        },
    "laser bean": {
        "name": "Laser Bean",
        "sun cost": "200",
        "recharge": "5 seconds",
        "damage": "40",
        "area": "Lane",
        "range": "Multi-Hit, all zombie in a lane",
        "family": "Spear-mint",
        "description": "Laser Beans fire down a lane, hitting all zombies ahead of it.",
        "image": "/assets/plants/Laser Bean.png"
        },
    "lava guava": {
        "name": "Lava Guava",
        "sun cost": "75",
        "recharge": "15 seconds",
        "damage": "200 damage per shot in a 3x3 area (initial eruption),100 damage per shot every 1 second (lava tile)",
        "area": "3x3 (initial eruption),Single tile (lava tile)",
        "range": "Touch",
        "usage": "Single use, on contact",
        "special": "Creates a burning lava pool in its tile",
        "weakness": "(Immune to fire)",
        "family": "Pepper-mint",
        "description": "Lava Guavas erupt, creating a lava pool that burns zombies.",
        "image": "/assets/plants/Lava Guava.png"
        },
    "lightning reed": {
        "name": "Lightning Reed",
        "sun cost": "125",
        "recharge": "5 seconds",
        "damage": "10",
        "range": "Multi-hit, can even hit targets one lane above or below",
        "special": "Chain attacks to multiple targets",
        "family": "Fila-mint",
        "description": "Lightning Reeds shoot lightning at nearest zombie up to one lane away. The bolt will then arc and hit other zombies.",
        "image": "/assets/plants/Lightning Reed.png"
        },
    "lily pad": {
        "name": "Lily Pad",
        "sun cost": "25",
        "recharge": "5 seconds",
        "toughness": "300 damage per shot",
        "usage": "Can also be planted under non-aquatic plants",
        "description": "Lily Pads let you plant non-aquatic plants on top of them.",
        "image": "/assets/plants/Lily Pad.png"
        },
    "magnet-shroom": {
        "name": "Magnet-shroom",
        "sun cost": "100",
        "recharge": "15 seconds",
        "range": "Multi-Lane",
        "special": "Removes metal objects from zombies",
        "family": "Contain-mint",
        "description": "Magnet-shrooms remove helmets and other metal objects from zombies.",
        "image": "/assets/plants/Magnet-shroom.png"
        },
    "magnifying grass": {
        "name": "Magnifying Grass",
        "sun cost": "50",
        "recharge": "5 seconds",
        "damage": "550",
        "special": "Tap to spend sun for an attack",
        "range": "Straight",
        "family": "Fila-mint",
        "description": "Magnifying Grass turns sun into a bolt of colorful damage.",
        "image": "/assets/plants/Magnifying Grass.png"
        },
    "melon-pult": {
        "name": "Melon-pult",
        "sun cost": "325",
        "recharge": "5 seconds",
        "damage": "80",
        "range": "Lobbed",
        "family": " Arma-mint",
        "description": "Melon-pults do heavy damage to groups of zombies.",
        "image": "/assets/plants/Melon-pult.png"
        },
    "missile toe": {
        "name": "Missile Toe",
        "sun cost": "500,400 (China)",
        "recharge": "5 seconds",
        "damage": "1200 damage per shot in a 1x3 area (Huge in China)",
        "area": "Tile,3x3 (China)",
        "usage": "Tap to arm, tap on target tile to fire",
        "family": "Winter-mint",
        "description": "Missile Toes launch cold blasts that damage, chill and slow zombies.",
        "image": "/assets/plants/Missile Toe.png"
        },
    "moonflower": {
        "name": "Moonflower",
        "sun cost": "50",
        "recharge": "10 seconds",
        "toughness": "Typical",
        "area": "3x3",
        "special": "Produces 25 more sun for each shadow plant nearby up to four.",
        "family": "Conceal-mint",
        "description": "Moonflowers radiate a glow that powers up adjacent Shadow plants.",
        "image": "/assets/plants/Moonflower.png"
        },
    "murkadamia nut": {
        "name": "Murkadamia Nut",
        "sun cost": "100",
        "recharge": "10 seconds",
        "toughness": "2500 damage per shot",
        "usage": "Damaged murk regrows over time",
        "family": "Conceal-mint",
        "description": "Murkadamia Nuts are defensive shadow plants who, when powered, grow jelly murk to damage attacking zombies.",
        "image": "/assets/plants/Murkadamia Nut.png"
        },
    "nightshade": {
        "name": "Nightshade",
        "sun cost": "75 (50 in Chinese version)",
        "recharge": "5 seconds",
        "damage": "100 damage per shot in 4 seconds (long range, powered),200 damage per shot in 4 seconds (close range),150 damage per shot in 4 seconds (long range, boosted),600 damage per shot in 4 seconds (close range, boosted)",
        "toughness": "300 DPS",
        "range": "Straight",
        "range details": "Close (not powered),Straight (powered)",
        "family": "Conceal-mint",
        "description": "Nightshades are shadow plants that smack zombies with slappy leaves.",
        "image": "/assets/plants/Nightshade.png"
        },
    "olive pit": {
        "name": "Olive Pit",
        "sun cost": "175",
        "recharge": "7 seconds",
        "usage": "Can swallow multiple zombies at a time",
        "special": "Spits out zombie-slowing olive oil",
        "family": "Contain-mint",
        "description": "Olive Pits drill into the ground and wait to consume zombies foolish enough to walk over them.",
        "image": "/assets/plants/Olive Pit.png"
        },
    "parsnip": {
        "name": "Parsnip",
        "sun cost": "150,125 (China)",
        "recharge": "5 seconds",
        "damage": "80 damage per shot,300 damage per shot (while rushing, every 0.2 seconds)",
        "range": "Close",
        "special": "Rushes at the last moment.",
        "family": "Enforce-mint",
        "description": "Parsnip snips at zombies, and then charges down the lane at the last moment.",
        "image": "/assets/plants/Parsnip.png"
        },
    "pea pod": {
        "name": "Pea Pod",
        "sun cost": "125",
        "recharge": "5 seconds",
        "damage": "20",
        "range": "Straight",
        "special": "Increases rate of fire with multiple plantings",
        "family": " Appease-mint",
        "description": "Pea Pods can be planted in the same space for up to 5 times the destruction.",
        "image": "/assets/plants/Pea Pod.png"
        },
    "pea vine": {
        "name": "Pea Vine",
        "sun cost": "125",
        "recharge": "5 seconds",
        "damage": "20",
        "special": "Boosts Appease-mint Family plants",
        "family": "Appease-mint",
        "description": "Pea Vines planted on top of Appease-mint Family plants provide a significant damage boost to those plants.",
        "image": "/assets/plants/Pea Vine.png"
        },
    "pea-nut": {
        "name": "Pea-nut",
        "sun cost": "150",
        "recharge": "15 seconds",
        "damage": "20 damage per shot",
        "toughness": "4000 damage per shot",
        "family": "Reinforce-mint",
        "description": "Pea-nuts can shoot peas and block zombies.",
        "image": "/assets/plants/Pea-nut.png"
        },
    "peashooter": {
        "name": "Peashooter",
        "sun cost": "100",
        "recharge": "5 seconds",
        "damage": "20",
        "toughness": "300",
        "range": "Straight",
        "powerup": "Duration",
        "family": "Appease-mint",
        "description": "Peashooters are your first line of defense. They shoot peas at attacking zombies.",
        "image": "/assets/plants/Peashooter.png"
        },
    "pepper-mint": {
        "name": "Pepper-mint",
        "sun cost": "0",
        "recharge": "85 seconds",
        "duration": "6 seconds",
        "weakness": "(immune to fire)",
        "family": "Pepper-mint",
        "description": "Pepper-mints set off lane-wide bursts of flame when planted and provide a temporary boost to all Pepper-mint plants on the lawn.",
        "image": "/assets/plants/Pepper-mint.png"
        },
    "pepper-pult": {
        "name": "Pepper-pult",
        "sun cost": "200",
        "recharge": "20 seconds",
        "damage": "50",
        "special": "Warms nearby tiles immune to frost",
        "range": "Lobbed",
        "family": "Pepper-mint",
        "description": "Pepper-pults lob flaming peppers at zombies and keeps nearby plants warm.",
        "image": "/assets/plants/Pepper-pult.png"
        },
    "perfume-shroom": {
        "name": "Perfume-shroom",
        "sun cost": "150",
        "recharge": "30 seconds",
        "usage": "Hypnotizes all dinosaurs in a lane",
        "description": "Perfume-shrooms enchant dinosaurs and charm them into working against the zombies.",
        "image": "/assets/plants/Perfume-shroom.png"
        },
    "potato mine": {
        "name": "Potato Mine",
        "sun cost": "25",
        "recharge": "20 seconds",
        "damage": "1800",
        "range": "Contact",
        "family": "Bombard-mint",
        "description": "Potato Mines explode on contact, but they take time to arm. Plant them ahead of zombies.",
        "image": "/assets/plants/Potato Mine.png"
        },
    "power lily": {
        "name": "Power Lily",
        "sun cost": "175",
        "recharge": "60 seconds",
        "usage": "Single use, instant",
        "description": "Power Lilies create one Plant Food out of thin air.",
        "image": "/assets/plants/Power Lily.png"
        },
    "power vine": {
        "name": "Power Vine",
        "sun cost": "150",
        "recharge": "5 seconds",
        "damage": "10 DPS per laser bolt",
        "special": "Power Vines horizontally or vertically adjacent to other Power Vines form a network",
        "family": "Fila-mint",
        "description": "Power Vines shoot rapid-fire, high-velocity laser bolts, and can increase their firepower by connecting up in a network.",
        "image": "/assets/plants/Power Vine.png"
        },
    "primal peashooter": {
        "name": "Primal Peashooter",
        "sun cost": "175",
        "recharge": "5 seconds",
        "damage": "50 damage per shot",
        "special": "Rock-like peas occasionally knock zombies back (in the Chinese version, his projectiles can stun or knockback zombies)",
        "family": "Appease-mint",
        "description": "Primal Peashooters shoot heavy peas with a brief stun and occasional knockback at zombies.",
        "image": "/assets/plants/Primal Peashooter.png"
        },
    "primal potato mine": {
        "name": "Primal Potato Mine",
        "sun cost": "50 (25 in Chinese version)",
        "recharge": "25 seconds",
        "damage": "2400 damage per shot",
        "area": "3x3",
        "range": "Contact",
        "usage": "Single use",
        "family": "Bombard-mint",
        "description": "Primal Potato Mines cost more than regular Potato Mines, but they arm more quickly and do damage over a larger area.",
        "image": "/assets/plants/Primal Potato Mine.png"
        },
    "primal sunflower": {
        "name": "Primal Sunflower",
        "sun cost": "75",
        "recharge": "5 seconds",
        "toughness": "300",
        "family": "Enlighten-mint",
        "description": "Primal Sunflowers pop out large suns instead of regular ones.",
        "image": "/assets/plants/Primal Sunflower.png"
        },
    "primal wall-nut": {
        "name": "Primal Wall-nut",
        "sun cost": "75",
        "recharge": "Fast",
        "toughness": "4000 damage per shot",
        "family": "Reinforce-mint",
        "description": "Primal Wall-nuts cost a bit more than typical Wall-nuts, but they can be planted much more quickly.",
        "image": "/assets/plants/Primal Wall-nut.png"
        },
    "puff-shroom": {
        "name": "Puff-shroom",
        "sun cost": "0",
        "recharge": "5 seconds",
        "damage": "20 damage per shot",
        "range": "3 Tiles",
        "special": "Lives for a limited time",
        "family": "Ail-mint",
        "description": "Puff-shrooms are short-range shooters that last for a limited time.",
        "image": "/assets/plants/Puff-shroom.png"
        },
    "puffball": {
        "name": "Puffball",
        "sun cost": "150",
        "recharge": "20 seconds",
        "area": "3x5",
        "usage": "Repeated Puffball explosions add to the poison",
        "family": "Ail-mint",
        "description": "Puffballs explode when planted, stunning and poisoning zombies in three columns.",
        "image": "/assets/plants/Puffball.png"
        },
    "pumpkin": {
        "name": "Pumpkin",
        "sun cost": "150",
        "recharge": "12 seconds",
        "toughness": "4000 damage per shot",
        "weakness": "(Can crush it)",
        "family": "Reinforce-mint",
        "description": "Pumpkins can be planted on top of other plants to provide a tough additional layer of armor.",
        "image": "/assets/plants/Pumpkin.png"
        },
    "pyre vine": {
        "name": "Pyre Vine",
        "sun cost": "125",
        "recharge": "10 seconds",
        "damage": "30 DPS",
        "weakness": "(Immune to fire)",
        "family": "Pepper-mint",
        "description": "Pyre Vines can be planted on top of other plants to provide protection from cold plus an additional close range flame attack.",
        "image": "/assets/plants/Pyre Vine.png"
        },
    "red stinger": {
        "name": "Red Stinger",
        "sun cost": "150",
        "recharge": "5 seconds",
        "damage": "30",
        "toughness": "300 damage per shot (columns 1-3)\n900 damage per shot (columns 4-6)\n1500 damage per shot (columns 7-9)",
        "range": "Straight",
        "family": "Appease-mint",
        "description": "Red Stingers fire shots at full force when close to home, and become more defensive further from it.",
        "image": "/assets/plants/Red Stinger.png"
        },
    "reinforce-mint": {
        "name": "Reinforce-mint",
        "sun cost": "0",
        "recharge": "85 seconds",
        "duration": "8 seconds",
        "special": "Knockback",
        "family": "Reinforce-mint",
        "description": "Reinforce-mints push all zombies back and provide a temporary boost to all Reinforce-mint Family plants on the lawn.",
        "image": "/assets/plants/Reinforce-mint.png"
        },
    "repeater": {
        "name": "Repeater",
        "sun cost": "200",
        "recharge": "5 seconds",
        "damage": "Moderate(normal for each pea)",
        "range": "Straight",
        "family": "Appease-mint",
        "description": "Repeater fires two peas at a time.",
        "image": "/assets/plants/Repeater.png"
        },
    "rotobaga": {
        "name": "Rotobaga",
        "sun cost": "150",
        "recharge": "5 seconds",
        "damage": "10",
        "special": "Fires in four direction",
        "range": "4 way",
        "family": "Appease-mint",
        "description": "Rotobagas shoot projectiles along the four diagonals, in each direction that has a target",
        "image": "/assets/plants/Rotobaga.png"
        },
    "sap-fling": {
        "name": "Sap-fling",
        "sun cost": "75 (150 in Chinese Version)",
        "recharge": "5 seconds",
        "area": "Tile",
        "range": "Lobbed",
        "damage details": "Does no damage on impact, but creates sap puddle",
        "special": "Slows zombies who walk in puddle",
        "family": "Contain-mint",
        "description": "Sap-flings create zombie-slowing puddles of sap.",
        "image": "/assets/plants/Sap-fling.png"
        },
    "shadow peashooter": {
        "name": "Shadow Peashooter",
        "sun cost": "125,200 (Chinese version)",
        "recharge": "5 seconds,Fast (Chinese version)",
        "damage": "30 damage per shot (peas),70 damage per shot (beam),Heavy (Chinese version)",
        "family": "Conceal-mint",
        "description": "Shadow Peashooters are shadow plants that fire piercing shadowy peas at zombies.",
        "image": "/assets/plants/Shadow Peashooter.png"
        },
    "shadow-shroom": {
        "name": "Shadow-shroom",
        "sun cost": "50",
        "recharge": "10 seconds (Mediocre in China)",
        "damage": "900 damage per shot over 30 seconds",
        "range": "Touch",
        "family": "Conceal-mint",
        "description": "Shadow-shrooms poison zombies who touch them, inflicting damage over time.",
        "image": "/assets/plants/Shadow-shroom.png"
        },
    "shine vine": {
        "name": "Shine Vine",
        "sun cost": "75",
        "recharge": "5 seconds",
        "damage": "5",
        "usage": "Best used on sun producer plants",
        "special": "Doesn't amplify Moonflower's sun production",
        "family": "Enlighten-mint",
        "description": "Shine Vines are vine plants that amplify the sun production of sun producer plants, except Moonflower, create some sun on their own, and use a sun-stun burst as a last second defense when attacked.",
        "image": "/assets/plants/Shine Vine.png"
        },
    "shrinking violet": {
        "name": "Shrinking Violet",
        "sun cost": "50",
        "recharge": "15 seconds",
        "area": "3x3",
        "usage": "Single use, activates when zombies are close",
        "special": "Shrinks Imps to oblivion",
        "family": "Enchant-mint",
        "description": "Shrinking Violets shrinks zombies in an area, forcing them to take double damage and reducing the bite damage they inflict.",
        "image": "/assets/plants/Shrinking Violet.png"
        },
    "snapdragon": {
        "name": "Snapdragon",
        "sun cost": "150",
        "recharge": "5 seconds",
        "damage": "30",
        "range": "Close",
        "special": "Damages all zombies in the 6 tiles in front of it",
        "family": " Pepper-mint",
        "description": "Snapdragons breathe fire that causes damage in 6 adjacent tiles.",
        "image": "/assets/plants/Snapdragon.png"
        },
    "solar sage": {
        "name": "Solar Sage",
        "sun cost": "0",
        "recharge": "20 seconds",
        "weakness": "Vulnerable to critters and mechs",
        "family": "Enlighten-mint",
        "description": "Solar Sages illuminate zombies, causing them to make better choices and depart, leaving behind a trail of sun.",
        "image": "/assets/plants/Solar Sage.png"
        },
    "solar tomato": {
        "name": "Solar Tomato",
        "sun cost": "100",
        "recharge": "25 seconds",
        "toughness": "Typical",
        "area": "3x3",
        "special": "Stun",
        "family": "Enlighten-mint",
        "description": "Solar Tomatoes stun zombies in a 3x3 area, causing each zombie to drop 50 sun.",
        "image": "/assets/plants/Solar Tomato.png"
        },
    "spear-mint": {
        "name": "Spear-mint",
        "sun cost": "0",
        "recharge": "85 seconds",
        "family": "Spear-mint",
        "description": "Spear-mints generate a number of higher-level Spikerocks on the board and provide a temporary boost to all Spear-mint Family plants on the lawn.",
        "image": "https://static.wikia.nocookie.net/plantsvszombies/images/0/00/Spear-mint2.png/revision/latest?cb=20190826045314"
        },
    "spikerock": {
        "name": "Spikerock",
        "sun cost": "250",
        "recharge": "5 seconds",
        "damage": "20",
        "area": "Tile",
        "special": "Can't be eaten by zombies",
        "weakness": "Can take three hits from rolling zombies",
        "family": "Spear-mint",
        "description": "Spikerocks destroy multiple rolling zombies and damage zombies that walk over it.",
        "image": "/assets/plants/Spikerock.png"
        },
    "spikeweed": {
        "name": "Spikeweed",
        "sun cost": "100",
        "recharge": "5 seconds",
        "damage": "10",
        "area": "Tile",
        "special": "Can't be eaten by zombies",
        "weakness": "Crushed by rolling zombies",
        "family": "Spear-mint",
        "description": "Spikeweeds destroy one rolling zombie and hurt any zombies that step on them.",
        "image": "/assets/plants/Spikeweed.png"
        },
    "split pea": {
        "name": "Split Pea",
        "sun cost": "125",
        "recharge": "5 seconds",
        "damage": "20",
        "range": "Front and Back",
        "family": "Appease-mint",
        "description": "Split Peas shoot peas forward and backwards.",
        "image": "/assets/plants/Split Pea.png"
        },
    "spore-shroom": {
        "name": "Spore-shroom",
        "sun cost": "150",
        "recharge": "5 seconds",
        "damage": "50 damage per shot",
        "range": "Lobbed",
        "family": "Ail-mint",
        "description": "Spore-shrooms fire spores that create new Spore-shrooms out of defeated zombies.",
        "image": "/assets/plants/Spore-shroom.png"
        },
    "spring bean": {
        "name": "Spring Bean",
        "sun cost": "50",
        "recharge": "20 seconds",
        "weakness": "Gets sleepy after springing",
        "range": "Touch",
        "special": "Pushes zombies back, or into the water",
        "family": "Contain-mint",
        "description": "Spring Beans bounce back zombies that get too close. Will bounce them into water if nearby.",
        "image": "/assets/plants/Spring Bean.png"
        },
    "squash": {
        "name": "Squash",
        "sun cost": "50, 125 (China)",
        "recharge": "20 seconds",
        "damage": "1800 damage per shot to each affected enemy",
        "toughness": "Elevated",
        "area": "All zombies around target",
        "range": "Close",
        "usage": "Single-use",
        "family": "Enforce-mint",
        "description": "Squashes will smash the first zombie that gets close.",
        "image": "/assets/plants/Squash.png"
        },
    "stallia": {
        "name": "Stallia",
        "sun cost": "0",
        "recharge": "20 seconds",
        "area": "3*3",
        "usage": "Single use, activates when zombie is close",
        "special": "Slows nearby zombies",
        "range": "Touch",
        "family": "Contain-mint",
        "description": "Stallias slow down zombies with a puff of perfume.",
        "image": "/assets/plants/Stallia.png"
        },
    "starfruit": {
        "name": "Starfruit",
        "sun cost": "150",
        "recharge": "5 seconds",
        "damage": "20 damage per shot per star",
        "toughness": "Normal",
        "range": "5 Way",
        "family": "Appease-mint",
        "description": "Starfruits shoot stars in 5 directions.",
        "image": "/assets/plants/Starfruit.png"
        },
    "stickybomb rice": {
        "name": "Stickybomb Rice",
        "sun cost": "225",
        "recharge": "10 seconds",
        "damage": "40 damage per shot",
        "special": "Exploding sticky bombs trigger other sticky bombs",
        "family": "Arma-mint",
        "description": "Stickybomb Rice lobs sticky rice bombs with timers at zombies.",
        "image": "/assets/plants/Stickybomb Rice.png"
        },
    "stunion": {
        "name": "Stunion",
        "sun cost": "25",
        "recharge": "20 seconds",
        "usage": "Single use, activates when zombie is close",
        "special": "Stuns nearby zombies",
        "range": "Close",
        "family": "contain-mint",
        "description": "Stunions breathe a stunning cloud of gas on nearby zombies in the lane.",
        "image": "/assets/plants/Stunion.png"
        },
    "sun bean": {
        "name": "Sun Bean",
        "sun cost": "50",
        "recharge": "20 seconds",
        "area": "Single",
        "usage": "Single use, on contact",
        "family": "Enlighten-mint",
        "description": "Sun Beans infect zombies with sun. As a zombie takes damage they generate sun.",
        "image": "/assets/plants/Sun Bean.png"
        },
    "sun-shroom": {
        "name": "Sun-shroom",
        "sun cost": "25",
        "recharge": "5 seconds",
        "toughness": "Typical",
        "family": "Enlighten-mint",
        "description": "Sun-shrooms give small sun at first, then normal suns, and finally large suns.",
        "image": "/assets/plants/Sun-shroom.png"
        },
    "sunflower": {
        "name": "Sunflower",
        "sun cost": "50",
        "recharge": "5 seconds",
        "sun-production": "Normal",
        "toughness": "300",
        "family": "Enlighten-mint",
        "description": "Sunflowers are essential for you to produce extra sun. Try planting as many as you can!",
        "image": "/assets/plants/Sunflower.png"
        },
    "sweet potato": {
        "name": "Sweet Potato",
        "sun cost": "150 (300 in China)",
        "recharge": "20 seconds",
        "toughness": "4000 damage per shot",
        "family": "Reinforce-mint",
        "description": "Sweet Potatoes attract zombies from other lanes when they are close by.",
        "image": "/assets/plants/Sweet Potato.png"
        },
    "tall-nut": {
        "name": "Tall-nut",
        "sun cost": "125",
        "recharge": "20 seconds",
        "toughness": "8000",
        "special": "Blocks launched imps",
        "family": " Reinforce-mint",
        "description": "Tall-nuts are heavy-duty wall plants that block low flying zombies.",
        "image": "/assets/plants/Tall-nut.png"
        },
    "tangle kelp": {
        "name": "Tangle Kelp",
        "sun cost": "25",
        "recharge": "20 seconds",
        "area": "Single",
        "range": "Touch",
        "family": "Enforce-mint",
        "description": "Tangle Kelp are aquatic plants that pull the first zombie that nears them underwater.",
        "image": "/assets/plants/Tangle Kelp.png"
        },
    "teleportato mine": {
        "name": "Teleportato Mine",
        "sun cost": "75",
        "recharge": "20 seconds",
        "damage": "2200",
        "toughness": "300",
        "area": "3x3",
        "usage": "Instant",
        "family": "Bombard-mint",
        "description": "Teleportato Mine teleports zombies to her location, then explodes.",
        "image": "/assets/plants/Teleportato Mine.png"
        },
    "threepeater": {
        "name": "Threepeater",
        "sun cost": "300",
        "recharge": "5 seconds",
        "damage": "Normal (for each pea)",
        "range": "Multi-Lane",
        "family": "Appease-mint",
        "description": "Threepeaters shoot peas in three lanes.",
        "image": "/assets/plants/Threepeater.png"
        },
    "thyme warp": {
        "name": "Thyme Warp",
        "sun cost": "75",
        "recharge": "60 seconds",
        "area": "Full Board",
        "usage": "Single use, instant",
        "special": "Rewound zombies have restored health",
        "family": "Contain-mint",
        "description": "Thyme Warps rewind time, sending zombies back where they started, but healing them in the process.",
        "image": "/assets/plants/Thyme Warp.png"
        },
    "tiger grass": {
        "name": "Tiger Grass",
        "sun cost": "150",
        "recharge": "7 seconds",
        "toughness": "40",
        "special": "Grass tiger grows over time",
        "family": "Enforce-mint",
        "description": "Tiger Grass spawns a tiger who leaps out to attack nearby zombies.",
        "image": "/assets/plants/Tiger Grass.png"
        },
    "tile turnip": {
        "name": "Tile Turnip",
        "sun cost": "0(First Tile Turnip) , 250 (price shown in almanc)",
        "recharge": 10,
        "usage": "Single use, instant",
        "description": "Tile Turnips create a Power Tile on planting.",
        "image": "/assets/plants/Tile Turnip.png"
        },
    "toadstool": {
        "name": "Toadstool",
        "sun cost": "200",
        "recharge": "5 seconds",
        "area": "Single",
        "range": "Close",
        "weakness": "Vulnerable while chewing",
        "family": "Enlighten-mint",
        "description": "Toadstools gulp down zombies whole, then produce sun.",
        "image": "/assets/plants/Toadstool.png"
        },
    "tumbleweed": {
        "name": "Tumbleweed",
        "sun cost": "50",
        "recharge": "5.5 seconds",
        "damage": "15",
        "range": "Straight",
        "special": "Set aflame by Torchwood",
        "family": "Appease-mint",
        "description": "Tumbleweeds roar off down the lane, bouncing off zombies and knocking them back with a chance to stun or even flip them off the lawn.",
        "image": "/assets/plants/Tumbleweed.png"
        },
    "twin sunflower": {
        "name": "Twin Sunflower",
        "sun cost": "125",
        "recharge": "10 seconds",
        "toughness": "300",
        "family": "Enlighten-mint",
        "description": "Twin Sunflowers give twice as much sun as a normal sunflower.",
        "image": "/assets/plants/Twin Sunflower.png"
        },
    "wall-nut": {
        "name": "Wall-nut",
        "sun cost": "50",
        "recharge": "20",
        "toughness": "4000",
        "powerup": "Armor",
        "family": "Reinforce-mint",
        "description": "Wall-nuts have hard shells which you can use to protect your other plants.",
        "image": "/assets/plants/Wall-nut.png"
        },
    "wasabi whip": {
        "name": "Wasabi Whip",
        "sun cost": "150",
        "recharge": "5 seconds",
        "damage": "40 damage per shot",
        "range": "Close",
        "special": "Resists cold and warms plants around it,(Immune to fire)",
        "family": "Enforce-mint",
        "description": "Wasabi Whips lash out with their flaming whips, delivering whuppings to zombies both in front and behind.",
        "image": "/assets/plants/Wasabi Whip.png"
        },
    "winter melon": {
        "name": "Winter Melon",
        "sun cost": "500",
        "recharge": "5 seconds",
        "damage": "80",
        "range": "Lobbed",
        "special": "Damaged enemies are also chilled",
        "family": "Winter-mint",
        "description": "Winter Melons do heavy damage and chills groups of zombies.",
        "image": "/assets/plants/Winter Melon.png"
        },
    "winter-mint": {
        "name": "Winter-mint",
        "sun cost": "0",
        "recharge": "85 seconds",
        "duration": "10 seconds",
        "family": "Winter-mint",
        "description": "Winter-mints chill all zombies present on the board when planted and provide a temporary boost to all Winter-mint Family plants on the lawn.",
        "image": "/assets/plants/Winter-mint.png"
        },
    "witch hazel": {
        "name": "Witch Hazel",
        "sun cost": "200",
        "recharge": "30 seconds",
        "special": "Prefers to target Wizard Zombies",
        "weakness": "(Cannot be turned into a mushroom)",
        "family": "Enchant-mint",
        "description": "Witch Hazels use magical sorcery to transform zombies into Puff-shrooms.",
        "image": "/assets/plants/Witch Hazel.png"
        },
    "zoybean pod": {
        "name": "Zoybean Pod",
        "sun cost": "200",
        "recharge": "20 seconds",
        "family": "Enchant-mint",
        "description": "Zoybean Pods grow from sprouts to full pods, then split open to release helpful plant 'zomboids' which attack zombies.",
        "image": "/assets/plants/Zoybean Pod.png"
        }
}